// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrYoDCaTbYh3prC8FCbSalW4WZpfYzNc4',
    appId: '1:649882463451:web:54d2dbd02a3c5641b6b0fe',
    messagingSenderId: '649882463451',
    projectId: 'test-b63ea',
    authDomain: 'test-b63ea.firebaseapp.com',
    storageBucket: 'test-b63ea.appspot.com',
    measurementId: 'G-S4ETHK8EHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8Vsa2B-qg8chuVTM7mOkvgnWJllEJTc',
    appId: '1:649882463451:android:bde2cbf7c59f1c66b6b0fe',
    messagingSenderId: '649882463451',
    projectId: 'test-b63ea',
    storageBucket: 'test-b63ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChLtux9Sh76oPtuxyX3CicB1v1Pkhkbd0',
    appId: '1:649882463451:ios:eac0030fef2d3f41b6b0fe',
    messagingSenderId: '649882463451',
    projectId: 'test-b63ea',
    storageBucket: 'test-b63ea.appspot.com',
    iosClientId: '649882463451-u8o3k9voqg8rn0f8cb86e5hjpo8f7bup.apps.googleusercontent.com',
    iosBundleId: 'com.tyger.velogsample',
  );
}
