// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8UCEdrO348FVYDZ30grMhH-ern2jX0UA',
    appId: '1:218277062103:web:8a4e78782849fcf0e91792',
    messagingSenderId: '218277062103',
    projectId: 'flip-it-cb0d4',
    authDomain: 'flip-it-cb0d4.firebaseapp.com',
    storageBucket: 'flip-it-cb0d4.appspot.com',
    measurementId: 'G-MZG3RSZXZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAlcmgth8FnoJ28QbrxlNs_hqc5CtfiTk',
    appId: '1:218277062103:android:687f58e2883a4fcce91792',
    messagingSenderId: '218277062103',
    projectId: 'flip-it-cb0d4',
    storageBucket: 'flip-it-cb0d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWY3OktRZMZw3FJm1GlqQW3RroubQuE1o',
    appId: '1:218277062103:ios:54e156e0898c3c12e91792',
    messagingSenderId: '218277062103',
    projectId: 'flip-it-cb0d4',
    storageBucket: 'flip-it-cb0d4.appspot.com',
    iosBundleId: 'com.takeoff.flipIt',
  );
}
